### ISSUE TITLE
Question amount not specified

### ISSUE THREAD

**Issue by Ririio** [mohitjaisal/quizapp#3]
I've noticed that when I type in the amount of questions needed, it never specifies what the problem is. This is a problem, because it's really up to the user to figure out how many questions they can have per game. 

What if instead of simply displaying the amount of questions available (I think that would require a lot of changes). We can decrease the question until we hit the maximum possible question for that specific category.

For example: If a user choose "50" questions for sports, instead of simply giving them an error, we can decrease the value of the "amount" until it hits "45" which is the valid value.

I specified 50, because that seems to be the max amount of questions you assigned per category. It might decrease the load time, but only by a little bit, because we are checking the url until the data length is more than 0

I can have the code ready if you'd want

**Comment by Ririio** [comment]
I can start it right away if you think it's a good idea

**Comment by mohitjaisal** [comment]
@Ririio are you still ready for it?

**Comment by Ririio** [comment]
sure I'll see what I can do with it
